For eCommittee
About e-Committee
The e-Committee, Supreme Court of India, welcomes you to this portal showcasing the Information and Communication Technology (ICT) initiatives adopted by the judicial system in India. The e-Committee is the governing body charged with overseeing the e-Courts Project conceptualized under the “National Policy and Action Plan for Implementation of Information and Communication Technology (ICT) in the Indian Judiciary-2005”. e-Courts is a pan India project monitored and funded by the Department of Justice, Ministry of Law and Justice, Government of India. Its vision is to transform the judicial system of the country by ICT enablement of courts.
For Privacy policy
Security
We are concerned about safeguarding the confidentiality of your information. We provide physical, electronic, and procedural safeguards to protect information we process and maintain. For example, we limit access to this information to authorized employees and contractors who need to know that information in order to operate, develop or improve our Application. Please be aware that, although we endeavour to provide reasonable security for information we process and maintain, no security system can prevent all potential security breaches.
Changes
This Privacy Policy may be updated from time to time for any reason. We will notify you of any changes to our Privacy Policy by posting the new Privacy Policy here. You are advised to consult this Privacy Policy regularly for any changes, as continued use is deemed approval of all changes.
Your Consent
By using the Application, you are consenting to our processing of your information as set forth in this Privacy Policy now and as amended by us.
For disclaimer
The information collected and shown on "eCourts Services" mobile application is an online open-content information of cases of pending or disposed cases by District Court and Taluka Courts in India. This information is shared by respective Court establishments from their local servers. Therefore, information provided on this mobile application, at best, of a general nature and cannot substitute for the authentic verified information, i.e., by a competent authority designated by each Court. Please contact concerned Court or Authority for complete, accurate or reliable information and please verify genuiness, veracity and authenticity of the information shown on this website. That is not to say that you will not find valuable and accurate information through this mobile application.

Neither the individual contributors, system operators, developers, NIC, eCommittee nor anyone else connected with this mobile appliation can take any responsibility for the results or consequences of any attempt to use or adopt any of the information or disinformation presented through this app.

Please make sure that you understand that the information provided here is being provided freely, and that no kind of agreement or contract is created between you and the owners or users of this site, the owners of the servers upon which it is housed, the individual contributors, any project administrators, project coordinators, sysops or anyone else who is in any way connected with this project or sister projects subject to your claims against them directly. You are being granted a limited license to view anything from this mobile application; it does not create or imply any contractual or extracontractual liability on the part of NIC or eCommittee or any of its agents, members, organizers or other users